title: Alisa Kunimoto Portfolio
logo: docs/assets/IMG_20250104_175820_524.jpg
description: Bioengineering Student @ UC San Diego
#show_downloads: true
theme: minima

header_pages:
  - about.md
  - projects.md
  - volunteering.md
  - resume.md
  - お礼状
